development:
    url:   <%= ENV['ELASTICSEARCH_URI'] || 'http://localhost:9200' %>
    index: licence-finder-development
    type:  sector

test:
    url:   <%= ENV['ELASTICSEARCH_URI'] || 'http://localhost:9200' %>
    index: licence-finder-test
    type:  sector

production:
    url:   <%= ENV['ELASTICSEARCH_URI'] || 'http://localhost:9200' %>
    index: licence-finder
    type:  sector

all_envs:
    extra_terms_filename: extra-terms.csv

    create:
        settings:
            analysis:
                analyzer:
                    my_start:
                        tokenizer: whitespace
                        filter: [asciifolding, lowercase, my_edge]
                    my_sort:
                        tokenizer: keyword
                        filter: [asciifolding, lowercase]
                    my_snowball:
                        tokenizer: standard
                        filter: [standard, lowercase, stop, my_synonym, my_snowball]
                filter:
                    my_edge:
                        type: edgeNGram
                        min_gram: 1
                        max_gram: 10
                        side: front
                    my_snowball:
                        type: snowball
                        language: English
                    my_synonym:
                        type: synonym
                        synonyms:
                            - "cafe, restaurant"
                            - "photography, photographic"
                            - "cleaner, clean"
        mappings:
            sector:
                properties:
                    public_id:
                        type:  keyword
                        store: yes
                        index: not_analyzed
                    title:
                        type: text
                        fields:
                            title:        {type: text, store: yes, index: analyzed, analyzer: my_snowball}
                            sortable:     {type: text, store: no,  index: analyzed, analyzer: my_snowball}
                            autocomplete: {type: text, store: no,  index: analyzed, analyzer: my_snowball}
                    extra_terms:
                        type: text
                        store: yes
                        index: analyzed
                        analyzer: my_snowball
                    activities:
                        type: text
                        store: yes
                        index: analyzed
                        analyzer: my_snowball
                        boost: 0.7
